{
 "title": "Evolution simulation",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Generic and static information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Game uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "evolution_running_seconds_total {job=\"evolution\"} / 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current generation",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "evolution_current_generation_number{job=\"evolution\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Creature brain topology",
     "type": "stat",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
     "targets": [
      {
       "expr": "evolution_creature_brain_topology_input_size{job=\"evolution\"}",
       "legendFormat": "Input signals"
      },
      {
       "expr": "evolution_creature_brain_topology_hidden_layer_sizes{job=\"evolution\"}",
       "legendFormat": "Hidden layers"
      },
      {
       "expr": "evolution_creature_brain_topology_hidden_layer_neurons{job=\"evolution\"}",
       "legendFormat": "Neurons per hidden layer"
      },
      {
       "expr": "evolution_creature_brain_topology_output_size{job=\"evolution\"}",
       "legendFormat": "Output signals"
      }
     ]
    }
   ]
  },
  { "title": "Creatures count metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Best creature scores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "evolution_best_herbivore_score{job=\"evolution\"}",
     "legendFormat": "Herbivores"
    },
    {
     "expr": "evolution_best_carnivore_score{job=\"evolution\"}",
     "legendFormat": "Carnivores"
    }
   ]
  },
  {
   "title": "Creatures count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "evolution_current_herbivore_count{job=\"evolution\"}",
     "legendFormat": "Herbivores"
    },
    {
     "expr": "evolution_current_carnivore_count{job=\"evolution\"}",
     "legendFormat": "Carnivores"
    }
   ]
  },
  {
   "title": "Food count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "evolution_current_food_count{job=\"evolution\"}",
     "legendFormat": "Food"
    }
   ]
  },
  {
   "title": "Genes info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Best herbivore genes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "evolution_best_herbivore_gene{job=\"evolution\"}",
     "legendFormat": "{{gene}}"
    }
   ]
  },
  {
   "title": "Best carnivore genes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "evolution_best_carnivore_gene{job=\"evolution\"}",
     "legendFormat": "{{gene}}"
    }
   ]
  }
 ]
}